// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/home.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/welcome.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/NavBar.tsx";
import * as $$2 from "./islands/ProfileImg.jsx";
import * as $$3 from "./islands/ToggleLightDark.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/home.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/welcome.tsx": $5,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/NavBar.tsx": $$1,
    "./islands/ProfileImg.jsx": $$2,
    "./islands/ToggleLightDark.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
